### ISSUE TITLE
Get rid of i-am-getting-horny-by-using-an-insecure-connection.headcounter.org

### ISSUE THREAD

**Issue by aszlig** [headcounter/deployment#2]
This virtual host is quite annoying as it needs quite a [lot](https://github.com/headcounter/deployment/blob/master/xmpp.nix#L34-L35) [of](https://github.com/headcounter/deployment/blob/master/xmpp.nix#L84-L90) [stupid](https://github.com/headcounter/deployment/blob/master/xmpp.nix#L282) [exceptions](https://github.com/headcounter/deployment/blob/master/xmpp.nix#L299-L304) in the configuration and it will even get messier after the refactoring of the vhost modules.

There is only **one** user on that virtual host and he's inactive since 5 years.

**Comment by aszlig** [comment]
Cc: @funkycode

**Comment by funkycode** [comment]
just saw it :)
i remember asking you to set account there for me, but not sure i used that nickname. 
So thanks for notifying.
P.S. internet is scary on gathering metadata on me ._.

**Comment by aszlig** [comment]
@funkycode: So, can I remove it or not? :-D

**Comment by funkycode** [comment]
sure man
